version: '2'
services:
  postgres:
    ports:
      - 54320:5432
    environment:
      POSTGRES_PASSWORD: postgres
  app:
    ports:
      - 80:8000
    command: bash -c "yarn docker:prod:start"
    environment:
      - NODE_ENV=production
      - SSH_AUTH_SOCK=/tmp/ssh-agent
    volumes:
      - "${SSH_AUTH_SOCK}:/tmp/ssh-agent"
