version: '2'
services:
  postgres:
    ports:
      - 54320:5432
    environment:
      POSTGRES_PASSWORD: postgres
  app:
    ports:
      - 8000:8000
      - 7000:7000
    command: yarn docker:dev:start
    environment:
      - NODE_ENV=development
      - SSH_AUTH_SOCK=/tmp/ssh-agent
    volumes:
      - "${SSH_AUTH_SOCK}:/tmp/ssh-agent"
