version: '2'
services:
  postgres:
    ports:
    environment:
      POSTGRES_PASSWORD: ${SSTK_SECRET}
  app:
    ports:
      - 80:8000
    command: yarn docker:prod:start
    environment:
      NODE_ENV: production
      POSTGRES_PASSWORD: ${SSTK_SECRET}
      SSTK_SECRET: ${SSTK_SECRET}
