version: '2'
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
    expose:
      - "5432"
    volumes:
      - ./var/lib/postgresql:/var/lib/postgresql/data
  app:
    build:
      context: .
    image: app
    volumes:
      - ./:/app
      - ./var/tmp:/tmp #used by Flow for caching
    links:
      - postgres
